      # ... (接在 Set up Android SDK 步骤之后)

      - name: Add Build Tools to PATH (将 Build Tools 添加到 PATH)
        run: |
          # ANDROID_HOME 通常由 setup-android action 设置
          # 找到最新版本的 build-tools 目录 (简单方法，可能需要根据实际情况调整)
          LATEST_BUILD_TOOLS_DIR=$(ls -t $ANDROID_HOME/build-tools | head -n 1)
          BUILD_TOOLS_PATH="$ANDROID_HOME/build-tools/$LATEST_BUILD_TOOLS_DIR"
          echo "Found latest build tools path: $BUILD_TOOLS_PATH"
          if [ -d "$BUILD_TOOLS_PATH" ]; then
            echo "Adding $BUILD_TOOLS_PATH to GITHUB_PATH"
            # 将路径添加到 GITHUB_PATH，使其在后续步骤中可用
            echo "$BUILD_TOOLS_PATH" >> $GITHUB_PATH
          else
            echo "::error::Could not find build tools directory: $BUILD_TOOLS_PATH"
            exit 1
          fi

      # 下一步才是 Verify APK and Print Certificate Info
      - name: Verify APK and Print Certificate Info (验证APK并打印证书信息)
        id: apk-verify
        run: |
          APK_FILE="downloaded_app.apk"
          echo "开始使用 apksigner 验证下载的 APK: ${APK_FILE}"
          # ... (后续脚本不变)
          # 现在应该能找到 apksigner 命令了
          apksigner_output=$(apksigner verify --print-certs "${APK_FILE}")
          # ... (后续错误检查和输出处理不变)
